version: '3'

services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: FLRPVcp41NC7mwD2TtX5
    networks:
      - cab_aggregator
    volumes:
      - mysql-data:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - cab_aggregator

  broker:
    image: confluentinc/cp-kafka
    container_name: broker
    restart: always
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - cab_aggregator

  eureka-server:
    image: cab-aggregator/eureka-server
    container_name: eureka-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - cab_aggregator
    depends_on:
      - mysql

  api-gateway:
    image: cab-aggregator/api-gateway
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans
    networks:
      - cab_aggregator
    depends_on:
      - mysql
      - eureka-server

  passenger-service:
    image: cab-aggregator/passenger-service
    container_name: passenger-service
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans
    ports:
      - '8081:8081'
    volumes:
      - logs:/app/logs
    networks:
      - cab_aggregator
    depends_on:
      - mysql
      - eureka-server

  driver-service:
    image: cab-aggregator/driver-service
    container_name: driver-service
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans
    ports:
      - "8082:8082"
    volumes:
      - logs:/app/logs
    networks:
      - cab_aggregator
    depends_on:
      - mysql
      - eureka-server

  payment-service:
    image: cab-aggregator/payment-service
    container_name: payment-service
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans
    ports:
      - "8083:8083"
    env_file:
      - .env
    volumes:
      - logs:/app/logs
    networks:
      - cab_aggregator
    depends_on:
      - mysql
      - eureka-server

  rating-service:
    image: cab-aggregator/rating-service
    container_name: rating-service
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans
    ports:
      - "8084:8084"
    volumes:
      - logs:/app/logs
    networks:
      - cab_aggregator
    depends_on:
      - mysql
      - eureka-server

  ride-service:
    image: cab-aggregator/ride-service
    container_name: ride-service
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans
    ports:
      - "8086:8086"
    volumes:
      - logs:/app/logs
    networks:
      - cab_aggregator
    depends_on:
      - mysql
      - eureka-server

  promocode-service:
    image: cab-aggregator/promocode-service
    container_name: promocode-service
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans
    ports:
      - "8085:8085"
    volumes:
      - logs:/app/logs
    networks:
      - cab_aggregator
    depends_on:
      - mysql
      - eureka-server

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    depends_on:
      - eureka-server
      - driver-service
      - passenger-service
      - payment-service
      - rating-service
      - promocode-service
      - ride-service
    networks:
      - cab_aggregator

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=DeVit1210
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - cab_aggregator

  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin-server
    restart: unless-stopped
    ports:
      - "9411:9411"
    networks:
      - cab_aggregator
    depends_on:
      - api-gateway

  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.ml.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - http.cors.allow-origin="*"
    networks:
      - cab_aggregator

  logstash:
    image: logstash:8.12.2
    container_name: logstash
    restart: unless-stopped
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - logs:/app/logs
    depends_on:
      - elasticsearch
    networks:
      - cab_aggregator

  kibana:
    image: kibana:8.12.2
    container_name: kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - cab_aggregator


networks:
  cab_aggregator:
    external: true

volumes:
  mysql-data:
  elasticsearch-data:
  logs: