server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=/passengers/**
          filters:
            - PrefixPath=/api/v1
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/drivers/**
          filters:
            - PrefixPath=/api/v1
        - id: ride-service
          uri: lb://ride-service
          predicates:
            - Path=/rides/**
            - Path=/ride-operations/**
            - Path=/ride/cost/**
          filters:
            - PrefixPath=/api/v1
        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/ratings/**
          filters:
            - PrefixPath=/api/v1
        - id: promocode-service
          uri: lb://promocode-service
          predicates:
            - Path=/promocodes/**
          filters:
            - PrefixPath=/api/v1
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
          filters:
            - PrefixPath=/api/v1
management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0