server:
  port: 8085
  servlet:
    context-path: /api/v1
spring:
  application:
    name: promocode-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/promocodes
    username: root
    password: FLRPVcp41NC7mwD2TtX5
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 1000
            read-timeout: 1000
resilience4j:
  retry:
    instances:
      ride-retry:
        max-attempts: 5
        wait-duration:
          nanos: 200
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - feign.FeignException.ServiceUnavailable
  circuitbreaker:
    instances:
      ride-circuit-breaker:
        sliding-window-type: count_based
        sliding-window-size: 10
        failure-rate-threshold: 75
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 75
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 10s
        max-wait-duration-in-half-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 5
management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"