spring:
  datasource:
    url: jdbc:mysql://mysql:3306/promocodes?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: FLRPVcp41NC7mwD2TtX5
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka