server:
  port: 8082
  servlet:
    context-path: /api/v1
spring:
  application:
    name: driver-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drivers
    username: root
    password: FLRPVcp41NC7mwD2TtX5
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: driver-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      properties:
        spring.json:
          trusted.packages: com.modsen.driver.dto.request
          type.mapping: ChangeDriverStatusRequest:com.modsen.driver.dto.request.ChangeDriverStatusRequest, FindDriverRequest:com.modsen.driver.dto.request.FindDriverRequest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: UpdateRideDriverRequest:com.modsen.driver.dto.request.UpdateRideDriverRequest
    producer-topic:
      name: ride-with-driver-topic
    ride-consumer-topic:
      name: rides-topic
    status-consumer-topic:
      name: driver-status-topic
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 1000
            read-timeout: 1000
      circuitbreaker:
        enabled: true
resilience4j:
  retry:
    instances:
      payment-retry:
        max-attempts: 2
        wait-duration: 3s
  circuitbreaker:
    instances:
      payment-circuit-breaker:
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 75
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 75
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 30s
        max-wait-duration-in-half-open-state: 30s
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 2