server:
  port: 8086
  servlet:
    context-path: /api/v1
spring:
  application:
    name: ride-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rides
    password: FLRPVcp41NC7mwD2TtX5
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connect-timeout: 1000
            read-timeout: 1000
  kafka:
    consumer:
      auto-offset-reset: latest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ride-service-group
      properties:
        spring.json:
          trusted.packages: com.modsen.dto.request,com.modsen.dto.response
          type.mapping: UpdateRideDriverRequest:com.modsen.ride.dto.request.UpdateRideDriverRequest
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: ChangeDriverStatusRequest:com.modsen.ride.dto.request.ChangeDriverStatusRequest, FindDriverRequest:com.modsen.ride.dto.request.FindDriverRequest
    ride-producer-topic:
      name: rides-topic
    status-producer-topic:
      name: driver-status-topic
    ride-consumer-topic:
      name: ride-with-driver-topic
ride:
  cost:
    start: 3.00
    per-kilometer: 1.50
feign:
  client:
    driver:
      name: driver-service
      url: /api/v1/drivers
    passenger:
      name: passenger-service
      url: /api/v1/passengers
    payment:
      name: payment-service
      url: /api/v1/payments
    promocode:
      name: promocode-service
      url: /api/v1/promocodes
