server:
  port: 8086
  servlet:
    context-path: /api/v1
spring:
  application:
    name: ride-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rides
    password: FLRPVcp41NC7mwD2TtX5
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

