spring:
  datasource:
    url: jdbc:mysql://mysql:3306/rides?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: FLRPVcp41NC7mwD2TtX5
  kafka:
    bootstrap-servers: broker:29092
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka